// probe/vitro_gen：Vitro 生成端 clone 实验（D-6 第一档「各语言自拼模板」实证）
// 把 Vitro scripts/moonbit/diagnostics_data/*.json 的生成出口改为直产 .json.mbt——
// 生成器自带类型知识（每张手写 struct 头），值体走通用渲染器（五条机械规则：
// 键去引号 / 值文本保形（json.Number）/ 尾逗号 / 字面量原样 / 头部 struct+let）。
// 验证链：产物 → jsonmbt check → jsonmbt build → 与原 JSON 值语义对拍。
//
// 运行：go run ./probe/vitro_gen <diagnostics_data 目录> <输出目录>
package main

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"strings"
)

// ── 通用值渲染（json.Number 保数值文本形态——Go float64 会把 1.0 变 1） ──

func mbtEscape(s string) string {
	r := strings.NewReplacer(
		`\`, `\\`, `"`, `\"`, "\n", `\n`, "\r", `\r`, "\t", `\t`, "\b", `\b`, "\f", `\f`,
	)
	return `"` + r.Replace(s) + `"`
}

func renderValue(v any) string {
	switch x := v.(type) {
	case string:
		return mbtEscape(x)
	case json.Number:
		return x.String() // 源文本保形（指数形态由 jsonmbt check 兜底——本数据面无指数）
	case bool:
		if x {
			return "true"
		}
		return "false"
	case []any:
		parts := make([]string, len(x))
		for i, e := range x {
			parts[i] = renderValue(e)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case map[string]any:
		// 对象：有 struct 头的类型不会走到这（各 doc 手写渲染）；此分支仅兜底
		parts := make([]string, 0, len(x))
		for _, k := range sortedKeys(x) {
			parts = append(parts, fmt.Sprintf("{ %s: %s }", mbtEscape(k), renderValue(x[k])))
		}
		return strings.Join(parts, ", ")
	default:
		fmt.Fprintf(os.Stderr, "unsupported value: %T\n", v)
		os.Exit(1)
		return ""
	}
}

func sortedKeys(m map[string]any) []string {
	// 顶层渲染按键序稳定即可（各 doc 的键序由手写渲染控制，这里不用于顶层）
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	// Go map 无序——确定性要求逐键手写，此函数仅限无序可容忍的兜底场景
	for i := 0; i < len(ks); i++ {
		for j := i + 1; j < len(ks); j++ {
			if ks[j] < ks[i] {
				ks[i], ks[j] = ks[j], ks[i]
			}
		}
	}
	return ks
}

func recordLine(k string, v any) string {
	return k + ": " + renderValue(v)
}

// ── 各 doc 的类型知识与渲染（生成器知道自己单源形态——D-6 第一档本义） ──

type fieldSpec struct {
	label string
	get   func(m map[string]any) string
}

func strField(label string) fieldSpec {
	return fieldSpec{label, func(m map[string]any) string { return mbtEscape(m[label].(string)) }}
}

func numField(label string) fieldSpec {
	return fieldSpec{label, func(m map[string]any) string { return m[label].(json.Number).String() }}
}

func arrField(label string) fieldSpec {
	return fieldSpec{label, func(m map[string]any) string { return renderValue(m[label]) }}
}

// elemRecord：数组元素是对象时，由调用方给字段序列（元素内联单行）
func renderDoc(stem, topStruct string, fields []docField, elems []elemSpec) string {
	var b strings.Builder
	fmt.Fprintf(&b, "// @generated by probe/vitro_gen —— 禁手改。\n// 源：Vitro diagnostics_data（单源形态）\n\n")
	for _, e := range elems {
		fmt.Fprintf(&b, "pub struct %s {\n", e.structName)
		for _, f := range e.fields {
			fmt.Fprintf(&b, "  %s : %s\n", f.label, f.ty)
		}
		b.WriteString("}\n\n")
	}
	fmt.Fprintf(&b, "pub struct %s {\n", topStruct)
	for _, f := range fields {
		fmt.Fprintf(&b, "  %s : %s\n", f.label, f.ty)
	}
	b.WriteString("}\n\n")
	fmt.Fprintf(&b, "pub let %s : %s = %s::{\n", stem, topStruct, topStruct)
	for _, f := range fields {
		fmt.Fprintf(&b, "  %s: %s,\n", f.label, f.render())
	}
	b.WriteString("}\n")
	return b.String()
}

type docField struct {
	label  string
	ty     string
	render func() string
}

type elemSpec struct {
	structName string
	fields     []struct {
		label string
		ty    string
	}
}

func main() {
	if len(os.Args) != 3 {
		fmt.Fprintln(os.Stderr, "usage: go run ./probe/vitro_gen <diagnostics_data> <outdir>")
		os.Exit(2)
	}
	srcDir, outDir := os.Args[1], os.Args[2]
	if err := os.MkdirAll(outDir, 0o755); err != nil {
		panic(err)
	}
	for _, doc := range buildDocs(srcDir) {
		out := filepath.Join(outDir, doc.stem+".json.mbt")
		if err := os.WriteFile(out, []byte(doc.content), 0o644); err != nil {
			panic(err)
		}
		fmt.Println("written:", out)
	}
}

type docProduct struct {
	stem    string
	content string
}

func loadDoc(srcDir, name string) map[string]any {
	raw, err := os.ReadFile(filepath.Join(srcDir, name))
	if err != nil {
		panic(err)
	}
	var m map[string]any
	dec := json.NewDecoder(strings.NewReader(string(raw)))
	dec.UseNumber()
	if err := dec.Decode(&m); err != nil {
		panic(err)
	}
	return m
}

func buildDocs(srcDir string) []docProduct {
	var out []docProduct

	// error_codes.json：{source_sha, arms: [Arm]}
	ec := loadDoc(srcDir, "error_codes.json")
	arms := ec["arms"].([]any)
	armLines := make([]string, len(arms))
	for i, a := range arms {
		m := a.(map[string]any)
		armLines[i] = "Arm::{ " + recordLine("name", m["name"]) + ", " + recordLine("code", m["code"]) + " }"
	}
	out = append(out, docProduct{"error_codes", renderDoc(
		"error_codes", "ErrorCodes",
		[]docField{
			{"source_sha", "String", strFieldTop(ec, "source_sha")},
			{"arms", "Array[Arm]", arrFieldTop(armLines)},
		},
		[]elemSpec{{"Arm", []struct {
			label string
			ty    string
		}{{"name", "String"}, {"code", "Int"}}}},
	)})

	// catalog.json：{source_sha, entries: [Entry]}
	cat := loadDoc(srcDir, "catalog.json")
	entries := cat["entries"].([]any)
	entryLines := make([]string, len(entries))
	for i, e := range entries {
		m := e.(map[string]any)
		entryLines[i] = "Entry::{ " + strings.Join([]string{
			recordLine("code", m["code"]), recordLine("emoji", m["emoji"]),
			recordLine("title", m["title"]), recordLine("explanation", m["explanation"]),
			recordLine("common_causes", m["common_causes"]),
		}, ", ") + " }"
	}
	out = append(out, docProduct{"catalog", renderDoc(
		"catalog", "Catalog",
		[]docField{
			{"source_sha", "String", strFieldTop(cat, "source_sha")},
			{"entries", "Array[Entry]", arrFieldTop(entryLines)},
		},
		[]elemSpec{{"Entry", []struct {
			label string
			ty    string
		}{{"code", "Int"}, {"emoji", "String"}, {"title", "String"}, {"explanation", "String"}, {"common_causes", "Array[String]"}}}},
	)})

	// patterns.json：{patterns: [Pattern], source_sha}
	pat := loadDoc(srcDir, "patterns.json")
	pats := pat["patterns"].([]any)
	patLines := make([]string, len(pats))
	for i, p := range pats {
		m := p.(map[string]any)
		patLines[i] = "Pattern::{ " + strings.Join([]string{
			recordLine("id", m["id"]), recordLine("name", m["name"]),
			recordLine("description", m["description"]), recordLine("error_codes", m["error_codes"]),
			recordLine("min_occurrences", m["min_occurrences"]), recordLine("time_window", m["time_window"]),
		}, ", ") + " }"
	}
	patSource := ""
	if v, ok := pat["source_sha"]; ok {
		patSource = v.(string)
	}
	out = append(out, docProduct{"patterns", renderDoc(
		"patterns", "Patterns",
		[]docField{
			{"patterns", "Array[Pattern]", arrFieldTop(patLines)},
			{"source_sha", "String", constStr(patSource)},
		},
		[]elemSpec{{"Pattern", []struct {
			label string
			ty    string
		}{{"id", "String"}, {"name", "String"}, {"description", "String"}, {"error_codes", "Array[Int]"}, {"min_occurrences", "Int"}, {"time_window", "Int"}}}},
	)})

	return out
}

func strFieldTop(m map[string]any, k string) func() string {
	return func() string { return mbtEscape(m[k].(string)) }
}

func arrFieldTop(lines []string) func() string {
	return func() string { return "[" + strings.Join(lines, ", ") + "]" }
}

func constStr(s string) func() string {
	return func() string { return mbtEscape(s) }
}
