// Package jsonmbt：JSON → .json.mbt 生成库（D-6 第二档「官方 emitter 微包
// jsonmbt-go」的实验雏形——独立于 MoonBit 工具链的第二实现）。
//
// 推断语义（与 MoonBit importer 的差异是有意登记的）：
//
//	单遍定型——同签名组按首见样本定型字段类型，后续样本只做值校验
//	（不做跨样本上浮聚合）；null 字段/空容器/异构/超 Int64 在无第二样本
//	可借时诚实拒绝（对齐 D-1/D-2 的阻断精神，非聚合实现）。
//
// 双实现面约束（PLAN D-6）：Go 产的 .json.mbt 经 jsonmbt build 降级后
// 必须与原 JSON 值语义等价——往返对拍即双实现对账锚。
package jsonmbt

import (
	"bytes"
	"encoding/json"
	"fmt"
	"sort"
	"strconv"
	"strings"
)

// Type：字段类型面（对齐 MoonBit JType 的可表达子集）
type Type interface{ String() string }

type TInt struct{}
type TInt64 struct{}
type TDouble struct{}
type TString struct{}
type TBool struct{}
type TOption struct{ Elem Type }
type TArray struct{ Elem Type }
type TMap struct{ Key, Val Type }
type TStruct struct{ Name string }

func (TInt) String() string      { return "Int" }
func (TInt64) String() string    { return "Int64" }
func (TDouble) String() string   { return "Double" }
func (TString) String() string   { return "String" }
func (TBool) String() string     { return "Bool" }
func (t TOption) String() string { return t.Elem.String() + "?" }
func (t TArray) String() string  { return "Array[" + t.Elem.String() + "]" }
func (t TMap) String() string    { return "Map[" + t.Key.String() + ", " + t.Val.String() + "]" }
func (t TStruct) String() string { return t.Name }

// Rejected：数据形态超出无损摄取面（对齐 MoonBit J4xxx 阻断——调用方按
// 「诚实拒绝」分流，不计为库缺陷）
type Rejected struct{ Reason string }

func (e *Rejected) Error() string { return "rejected: " + e.Reason }

// ── 推断器（单遍定型） ──

type groupDef struct {
	name       string
	keys       []string // 首见键序（渲染序 = 源序）
	fieldTypes map[string]Type
}

type inferrer struct {
	groups    map[string]*groupDef // 签名 → 组
	order     []*groupDef
	usedNames map[string]bool
	stem      string
}

// Generate：JSON 文本 → .json.mbt 全文
func Generate(stem, srcName string, jsonText []byte) (string, error) {
	dec := json.NewDecoder(bytes.NewReader(jsonText))
	dec.UseNumber()
	var root any
	if err := dec.Decode(&root); err != nil {
		return "", fmt.Errorf("invalid JSON: %w", err)
	}
	// stem 清洗为合法 binding（label 域标识符——"array_address.c" 这类文件名
	// 直接作 stem 会产非法 pub let；与类型名清洗同族）
	stem = sanitizeLabel(stem)
	inf := &inferrer{groups: map[string]*groupDef{}, usedNames: map[string]bool{}, stem: stem}
	rootTy, err := inf.infer(root)
	if err != nil {
		return "", err
	}
	if topMap, ok := root.(map[string]any); ok && len(topMap) > 0 {
		// 顶层组名固定为 capitalize(stem)（D-7 同源）；改名后同步 rootTy
		// （不同步则类型注解用旧名 → 查组失败 → 值体掉进 Map 渲染）
		if g := inf.groups[signatureOf(keysOf(topMap))]; g != nil {
			inf.usedNames[g.name] = false
			g.name = inf.allocName(capitalize(stem))
			rootTy = TStruct{g.name}
		}
	}
	var b strings.Builder
	fmt.Fprintf(&b, "// @generated by jsonmbt-go —— 禁手改（源：%s）。\n\n", srcName)
	for _, g := range inf.order {
		b.WriteString("pub struct " + g.name + " {\n")
		for _, k := range g.keys {
			fmt.Fprintf(&b, "  %s : %s\n", k, g.fieldTypes[k].String())
		}
		b.WriteString("}\n\n")
	}
	if _, isMap := root.(map[string]any); isMap && rootTy != nil {
		fmt.Fprintf(&b, "pub let %s : %s = %s\n", stem, rootTy.String(), inf.renderTop(root, rootTy))
	} else {
		fmt.Fprintf(&b, "pub let %s = %s\n", stem, inf.render(root, nil))
	}
	return b.String(), nil
}

// renderTop：根值渲染（struct 根 = 多行形态；其余内联）
func (inf *inferrer) renderTop(root any, ty Type) string {
	if st, ok := ty.(TStruct); ok {
		if g := inf.groupByName(st.Name); g != nil {
			if m, ok2 := root.(map[string]any); ok2 {
				var b strings.Builder
				b.WriteString(st.Name + "::{\n")
				for _, k := range g.keys {
					if val, ok3 := m[k]; ok3 {
						fmt.Fprintf(&b, "  %s: %s,\n", k, inf.render(val, g.fieldTypes[k]))
					}
				}
				b.WriteString("}")
				return b.String()
			}
		}
	}
	return inf.render(root, ty)
}

func (inf *inferrer) groupByName(name string) *groupDef {
	for _, g := range inf.order {
		if g.name == name {
			return g
		}
	}
	return nil
}

func (inf *inferrer) infer(v any) (Type, error) {
	switch x := v.(type) {
	case nil:
		return nil, &Rejected{"bare null (no type context)"}
	case bool:
		return TBool{}, nil
	case json.Number:
		t := x.String()
		if !strings.ContainsAny(t, ".eE") {
			if i, err := strconv.ParseInt(t, 10, 64); err == nil {
				if i >= -2147483648 && i <= 2147483647 {
					return TInt{}, nil
				}
				return TInt64{}, nil
			}
			return nil, &Rejected{"integer exceeds Int64: " + t}
		}
		return TDouble{}, nil
	case string:
		return TString{}, nil
	case []any:
		if len(x) == 0 {
			return nil, &Rejected{"empty array (no element-type clue)"}
		}
		elemTy, err := inf.infer(x[0])
		if err != nil {
			return nil, err
		}
		elemTy = stripOption(elemTy) // 数组元素统一非 Option（值位 null 数组元素=异构）
		for _, e := range x[1:] {
			t, err := inf.infer(e)
			if err != nil {
				return nil, err
			}
			if !valueCompatible(elemTy, t) {
				return nil, &Rejected{"heterogeneous array: " + elemTy.String() + " vs " + t.String()}
			}
		}
		return TArray{elemTy}, nil
	case map[string]any:
		if len(x) == 0 {
			return nil, &Rejected{"empty object"}
		}
		keys := keysOf(x) // map 迭代序不稳定——键序在组首见时定格
		allLegal := true
		for _, k := range keys {
			if !isLegalLabel(k) {
				allLegal = false
				break
			}
		}
		if !allLegal {
			return inf.inferAsMap(x, keys)
		}
		return inf.inferAsStruct(x, keys)
	}
	return nil, fmt.Errorf("unsupported value %T", v)
}

// inferAsStruct：签名查组；首见定型，后续样本值校验
func (inf *inferrer) inferAsStruct(x map[string]any, keys []string) (Type, error) {
	sig := signatureOf(keys)
	g := inf.groups[sig]
	if g == nil {
		g = &groupDef{keys: keys, fieldTypes: map[string]Type{}}
		inf.groups[sig] = g
		inf.order = append(inf.order, g)
		for _, k := range keys {
			t, err := inf.infer(x[k])
			if err != nil {
				return nil, err
			}
			g.fieldTypes[k] = t
		}
		g.name = inf.allocName(capitalize(keys[0]))
		return TStruct{g.name}, nil
	}
	// 后续样本：值形态须与已定型字段类型相容（Int 样本落在 Int64/Double 字段
	// 可相容；跨域即拒——单遍定型语义，不做上浮）
	for _, k := range keys {
		t, err := inf.infer(x[k])
		if err != nil {
			return nil, err
		}
		if !valueCompatible(g.fieldTypes[k], t) {
			return nil, &Rejected{
				"field '" + k + "' type drift: " + g.fieldTypes[k].String() + " vs " + t.String(),
			}
		}
	}
	return TStruct{g.name}, nil
}

// inferAsMap：键名逃生门（值同构；null 值跳过定性——全 null 拒）
func (inf *inferrer) inferAsMap(x map[string]any, keys []string) (Type, error) {
	var valTy Type
	for _, k := range keys {
		if x[k] == nil {
			continue
		}
		t, err := inf.infer(x[k])
		if err != nil {
			return nil, err
		}
		if valTy == nil {
			valTy = t
		} else if !valueCompatible(valTy, t) {
			return nil, &Rejected{"mixed-value map values: " + valTy.String() + " vs " + t.String()}
		}
	}
	if valTy == nil {
		return nil, &Rejected{"map values all null"}
	}
	return TMap{TString{}, valTy}, nil
}

// valueCompatible：值形态 t 能否落在已定型类型 slot 上
func valueCompatible(slot Type, t Type) bool {
	if slot == nil || t == nil {
		return false
	}
	if so, ok := slot.(TOption); ok {
		return valueCompatible(so.Elem, t)
	}
	if sameKind(slot, t) {
		switch sv := slot.(type) {
		case TArray:
			tv := t.(TArray)
			return valueCompatible(sv.Elem, tv.Elem) || isEmpty(tv.Elem)
		case TMap:
			tv := t.(TMap)
			return valueCompatible(sv.Val, tv.Val)
		case TStruct:
			tv := t.(TStruct)
			return sv.Name == tv.Name
		}
		return true
	}
	// 数值域宽容：Int 值可落 Int64/Double 字段（MoonBit 定型同款）；反向不可
	if isNumeric(slot) && isNumeric(t) {
		slotRank := numRank(slot)
		tRank := numRank(t)
		return slotRank >= tRank || slotRank == 2 // Double 吃一切数值（JSON 值语义无损：文本保形）
	}
	return false
}

func isEmpty(t Type) bool {
	return t == nil
}

func isNumeric(t Type) bool {
	switch t.(type) {
	case TInt, TInt64, TDouble:
		return true
	}
	return false
}

func numRank(t Type) int {
	switch t.(type) {
	case TInt:
		return 0
	case TInt64:
		return 1
	case TDouble:
		return 2
	}
	return -1
}

func stripOption(t Type) Type {
	if o, ok := t.(TOption); ok {
		return o.Elem
	}
	return t
}

func sameKind(a, b Type) bool {
	switch a.(type) {
	case TInt:
		_, ok := b.(TInt)
		return ok
	case TInt64:
		_, ok := b.(TInt64)
		return ok
	case TDouble:
		_, ok := b.(TDouble)
		return ok
	case TString:
		_, ok := b.(TString)
		return ok
	case TBool:
		_, ok := b.(TBool)
		return ok
	case TOption:
		_, ok := b.(TOption)
		return ok
	case TArray:
		_, ok := b.(TArray)
		return ok
	case TMap:
		_, ok := b.(TMap)
		return ok
	case TStruct:
		_, ok := b.(TStruct)
		return ok
	}
	return false
}

func (inf *inferrer) allocName(base string) string {
	c := sanitizeTypeName(capitalize(base))
	if !isLegalTypeName(c) {
		c = sanitizeTypeName(capitalize(inf.stem))
	}
	if !isLegalTypeName(c) {
		c = "Root"
	}
	if !inf.usedNames[c] {
		inf.usedNames[c] = true
		return c
	}
	for i := 2; ; i++ {
		n := c + strconv.Itoa(i)
		if !inf.usedNames[n] {
			inf.usedNames[n] = true
			return n
		}
	}
}

// ── 命名合法性（对齐 infer.mbt 全字符验证） ──

var reservedLabels = map[string]bool{
	"fn": true, "let": true, "mut": true, "const": true, "return": true,
	"match": true, "if": true, "else": true, "loop": true, "while": true,
	"for": true, "in": true, "break": true, "continue": true, "true": true,
	"false": true, "struct": true, "enum": true, "type": true, "trait": true,
	"impl": true, "pub": true, "priv": true, "package": true, "import": true,
	"test": true, "as": true, "extern": true, "raise": true, "try": true,
	"catch": true, "defer": true, "guard": true, "when": true, "view": true,
	"extenum": true, "async": true, "backed": true, "where": true, "is": true,
	"unit": true,
}

// sanitizeTypeName：清洗非法字符（点/横线/空格等 → 下划线）——
// 与 label 全字符验证同族（jsonmbt-go 曾只验首字符，"array_address.c"
// 作 stem 时产非法类型名——MoonBit 侧刚修的同款形态）
func sanitizeTypeName(n string) string {
	var b strings.Builder
	for i, r := range n {
		switch {
		case r >= 'A' && r <= 'Z', r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_':
			if i == 0 && r >= '0' && r <= '9' {
				b.WriteRune('_')
			}
			b.WriteRune(r)
		default:
			b.WriteRune('_')
		}
	}
	out := b.String()
	if out == "" || out == "_" {
		return "Root"
	}
	return out
}

// sanitizeLabel：binding 名清洗（非法字符→下划线，首字符非小写字母/下划线
// 则前缀 x_；纯清洗后空则 "x"）
func SanitizeStem(n string) string {
	return sanitizeLabel(n)
}

func sanitizeLabel(n string) string {
	if n == "" {
		return "x"
	}
	var b strings.Builder
	for _, r := range n {
		switch {
		case r >= 'a' && r <= 'z', r >= '0' && r <= '9', r == '_', r >= 0x80:
			b.WriteRune(r)
		case r >= 'A' && r <= 'Z':
			b.WriteRune(r + 32) // binding 域小写化
		default:
			b.WriteRune('_')
		}
	}
	out := b.String()
	first := out[0]
	if !(first >= 'a' && first <= 'z') && first != '_' && first < 0x80 {
		out = "x_" + out
	}
	if first >= '0' && first <= '9' {
		out = "x_" + out
	}
	return out
}

func isLegalLabel(name string) bool {
	if name == "" || reservedLabels[name] {
		return false
	}
	for i, r := range name {
		if i == 0 {
			if r == '_' || r >= 0x80 || (r >= 'a' && r <= 'z') {
				continue
			}
			return false
		}
		switch {
		case r >= 'a' && r <= 'z', r >= 'A' && r <= 'Z', r >= '0' && r <= '9', r == '_', r >= 0x80:
		default:
			return false
		}
	}
	return true
}

func isLegalTypeName(n string) bool {
	if n == "" {
		return false
	}
	r := []rune(n)[0]
	return r >= 'A' && r <= 'Z'
}

func capitalize(s string) string {
	if s == "" {
		return s
	}
	r := []rune(s)
	if r[0] >= 'a' && r[0] <= 'z' {
		r[0] -= 32
	}
	return string(r)
}

// keysOf：排序键序——encoding/json 的 map 无序，Go 侧键序恒排序
// （与 MoonBit importer 的「源文本序」有意不同：往返锚比对值语义不比文本；
// 差异登记于 D-6 双实现面）
func keysOf(m map[string]any) []string {
	ks := make([]string, 0, len(m))
	for k := range m {
		ks = append(ks, k)
	}
	sort.Strings(ks)
	return ks
}

func signatureOf(keys []string) string {
	s := append([]string(nil), keys...)
	sort.Strings(s)
	return strings.Join(s, "\x01")
}

// ── 渲染（顶层 record 多行；嵌套内联单行——fmt-canonical） ──

func mbtEscape(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		case '\b':
			b.WriteString(`\b`)
		case '\f':
			b.WriteString(`\f`)
		default:
			if r < 0x20 {
				fmt.Fprintf(&b, "\\u{%d}", int(r))
			} else {
				b.WriteRune(r)
			}
		}
	}
	b.WriteByte('"')
	return b.String()
}

// ensureDoubleSyntax：纯整数尾数 + 指数补 ".0"（MoonBit 文法——陷阱 #13 勘误）
func ensureDoubleSyntax(repr string) string {
	ei := strings.IndexAny(repr, "eE")
	if ei < 0 || strings.Contains(repr[:ei], ".") {
		return repr
	}
	return repr[:ei] + ".0" + repr[ei:]
}

// render：值 → MoonBit 字面量（期望类型驱动：struct 位→Name::{}、map 位→{}）
func (inf *inferrer) render(v any, ty Type) string {
	if v == nil {
		return "None"
	}
	switch x := v.(type) {
	case bool:
		if x {
			return "true"
		}
		return "false"
	case json.Number:
		return ensureDoubleSyntax(x.String())
	case string:
		return mbtEscape(x)
	case []any:
		if at, ok := ty.(TArray); ok {
			// null 元素在 Option 元素型下渲染 Some/None——值位 null 数组元素
			// 已在推断层拒（异构），此处元素型必非 Option
			parts := make([]string, len(x))
			for i, e := range x {
				parts[i] = inf.render(e, at.Elem)
			}
			return "[" + strings.Join(parts, ", ") + "]"
		}
		parts := make([]string, len(x))
		for i, e := range x {
			parts[i] = inf.render(e, nil)
		}
		return "[" + strings.Join(parts, ", ") + "]"
	case map[string]any:
		if st, ok := ty.(TStruct); ok {
			g := inf.groupByName(st.Name)
			if g != nil {
				var lines []string
				for _, k := range g.keys { // struct 位：按组键序（首见序）
					if val, ok := x[k]; ok {
						lines = append(lines, k+": "+inf.render(val, g.fieldTypes[k]))
					}
				}
				return st.Name + "::{ " + strings.Join(lines, ", ") + " }"
			}
		}
		// Map 位 / 自由对象：按键排序稳定输出
		ks := keysOf(x)
		sort.Strings(ks)
		parts := make([]string, len(ks))
		var vt Type
		if mt, ok := ty.(TMap); ok {
			vt = mt.Val
		}
		for i, k := range ks {
			parts[i] = mbtEscape(k) + ": " + inf.render(x[k], vt)
		}
		return "{ " + strings.Join(parts, ", ") + " }"
	}
	return "?"
}
